export const REQUEST_POSTS = 'REQUEST_POSTS'
export const POSTS_SUCCESS = 'POSTS_SUCCESS'
export const POSTS_FAILED = 'POSTS_FAILED'

export const UPDATE_SORT_BY = 'UPDATE_SORT_BY'
export const TOGGLE_SORT_ORDER = 'TOGGLE_SORT_ORDER'

export const TOGGLE_GROUP_BY_USER_ID = 'TOGGLE_GROUP_BY_USER_ID'
